import argparse
import os
import subprocess
import json
import sys

def extract_frames(json_file):
    if not os.path.exists(json_file):
        print(json.dumps({"error": f"JSON file not found: {json_file}"}))
        sys.exit(1)
        
    with open(json_file, "r", encoding="utf-8") as f:
        data = json.load(f)
        
    characters = data.get("main_characters", [])
    results = []
    
    for item in characters:
        name = str(item.get("person_name", "unknown")).replace(" ", "_")
        timestamp = str(item.get("time_stamp", "00:00:00"))
        video_path = item.get("source_video")
        
        if not video_path or not os.path.exists(video_path):
            results.append({"name": name, "error": f"Invalid video path: {video_path}"})
            continue
            
        # Determine out_dir: repo/S2_Video_Understanding/<video_name>/faces/
        vid_basename = os.path.splitext(os.path.basename(video_path))[0]
        out_dir = os.path.join("repo", "S2_Video_Understanding", vid_basename, "faces")
        os.makedirs(out_dir, exist_ok=True)
        
        out_path = os.path.join(out_dir, f"{name}.jpg")
        
        # Frame accurate seek: -i video -ss timestamp
        cmd = [
            "ffmpeg", "-y", "-i", video_path, "-ss", timestamp,
            "-vframes", "1", "-q:v", "2", out_path
        ]
        
        try:
            subprocess.run(cmd, check=True, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
            if os.path.exists(out_path):
                results.append({"name": name, "timestamp": timestamp, "path": out_path, "status": "success"})
                item["face_image_path"] = out_path # Update JSON with local path
            else:
                results.append({"name": name, "timestamp": timestamp, "error": "File not generated", "status": "failed"})
        except Exception as e:
            results.append({"name": name, "timestamp": timestamp, "error": str(e), "status": "failed"})
            
    # Write back the updated JSON
    with open(json_file, "w", encoding="utf-8") as f:
        json.dump(data, f, indent=2, ensure_ascii=False)
        
    print(json.dumps(results, indent=2))

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Extract specific frames from a video using ffmpeg and a JSON file")
    parser.add_argument("--json_file", required=True, help="Path to the JSON file generated by gemini_video_understanding.py")
    
    args = parser.parse_args()
    extract_frames(args.json_file)
